---
title: "行政法［司法試験対策］"
date: 2/17/2024
categories: [行政法, 司法試験対策]
---

## R5


* 処分性
    * 病院開設中止勧告事件(最判平成17年7月15日民集59巻6号1661頁)

> 上記の医療法及び健康保険法の規定の内容やその運用の実情に照らすと，医療法３０条の７の規定に基づく病院開設中止の勧告は，医療法上は当該勧告を受けた者が任意にこれに従うことを期待してされる行政指導として定められているけれども，当該勧告を受けた者に対し，これに従わない場合には，相当程度の確実さをもって，病院を開設しても保険医療機関の指定を受けることができなくなるという結果をもたらすものということができる。そして，いわゆる国民皆保険制度が採用されている我が国においては，健康保険，国民健康保険等を利用しないで病院で受診する者はほとんどなく，保険医療機関の指定を受けずに診療行為を行う病院がほとんど存在しないことは公知の事実であるから，保険医療機関の指定を受けることができない場合には，実際上病院の開設自体を断念せざるを得ないことになる。このような医療法３０条の７の規定に基づく病院開設中止の勧告の保険医療機関の指定に及ぼす効果及び病院経営における保険医療機関の指定の持つ意義を併せ考えると，この勧告は，行政事件訴訟法３条２項にいう「行政庁の処分その他公権力の行使に当たる行為」に当たると解するのが相当である。後に保険医療機関の指定拒否処分の効力を抗告訴訟によって争うことができるとしても，そのことは上記の結論を左右するものではない。

救済のタイミングの考慮

相当程度の確実な連動＋後続処分の不利益性の深刻度（実効的救済の困難）

ちなみに、この判例は前倒し的な法効果に言及していない点で特徴的。これは、勧告不服従に対する指定拒否を許容はするけれど、指定拒否処分（後続処分）との連動性が相対的には弱かったからではないか？

* 原告適格
    * 処分の名宛人以外の者についても認めた事案
    第二次納税義務者に不服申立適格を認めた事例（最判平成18年1月19日民集60巻1号65頁）
    
    滞納者の財産が差し押さえられた場合の当該財産の共有者に原告適格を認めた事例（最判平25 年7月12日集民244号43頁）
    * 複数の処分の効果の連動（ただし、平成18年判決の方がその連動は弱く、主たる課税処分の時点では第二次納税義務者に対する課税処分が確定しているわけではない）
    * 「処分の名宛人以外の者が処分の法的効果による権利の制限を受ける場合には，その者は，処分の名宛人として権利の制限を受ける者と同様に，当該処分により自己の権利を侵害され又は必然的に侵害されるおそれのある者として，当該処分の取消しを求めるにつき法律上の利益を有する者に当たり，その取消訴訟における原告適格を有する」
    * 行訴法第9条第2項による検討を経ることなく、「法律上の利益」の有無を論じた（処分の相手方に準じる立場にある者）
* 執行停止の申立て（行訴法25条）「重大な損害」の有無
    * 最決平成19年12月18日集民226号603頁
    * 25条3項に掲げられる事項と事実関係との結びつき
* 裁量権の逸脱濫用
    * 他事考慮・考慮不尽
    * 比例原則
